import 'dart:ui';

import 'product_model.dart';

class Constants {
  static List<ProductModel> chairs = [
    ProductModel(
      id: 1,
      imagePath: 'assets/images/sofa.png',
      glbSource: 'assets/models/sofa.glb',
      extraGlb: 'assets/models/sofa2.glb',
      name: 'Sofa',
      productType: 'Furniture',
      description: 'Product',
      primcolor: Color(0xffa19f9c),
      extracolor: Color(0xffd64444),
    ),
    ProductModel(
      id: 2,
      imagePath: 'assets/images/chair.png',
      glbSource: 'assets/models/chair.glb',
      extraGlb: 'assets/models/chair2.glb',
      name: 'Chair',
      productType: 'Furniture',
      description: 'Product',
      primcolor: Color(0xff075045),
      extracolor: Color(0xff8e6a22),
    ),
    ProductModel(
      id: 3,
      imagePath: 'assets/images/table.png',
      glbSource: 'assets/models/table.glb',
      extraGlb: 'assets/models/table2.glb',
      name: 'Table',
      productType: 'Furniture',
      description: 'Product',
      primcolor: Color(0xff777668),
      extracolor: Color(0xff511749),
    ),
    ProductModel(
      id: 4,
      imagePath: 'assets/images/Refrigerator.png',
      glbSource: 'assets/models/refrigerator.glb',
      extraGlb: 'assets/models/refrigerator2.glb',
      name: 'Refrigerator',
      productType: 'Home Appliences',
      description: 'Product',
      primcolor: Color(0xffa2a2a2),
      extracolor: Color(0xff85bdca),
    ),
    ProductModel(
      id: 5,
      imagePath: 'assets/images/washingmachine.png',
      glbSource: 'assets/models/washingmachine.glb',
      extraGlb: 'assets/models/washingmachine2.glb',
      name: 'Washing Machine',
      productType: 'Home Appliences',
      description: 'Product',
      primcolor: Color(0xffa19f9c),
      extracolor: Color(0xffc9ad9d),
    ),
    ProductModel(
      id: 6,
      imagePath: 'assets/images/bed.png',
      glbSource: 'assets/models/bed.glb',
      extraGlb: 'assets/models/bed2.glb',
      name: 'Single Bed',
      productType: 'Furniture',
      description: 'Product',
      primcolor: Color(0xffffffff),
      extracolor: Color(0xff640606),
    ),
    ProductModel(
      id: 7,
      imagePath: 'assets/images/microwave.png',
      glbSource: 'assets/models/microwave.glb',
      extraGlb: 'assets/models/microwave2.glb',
      name: 'Microwave',
      productType: 'Electronics',
      description: 'Product',
      primcolor: Color(0xfff7f7f7),
      extracolor: Color(0xff524b4b),
    ),
    ProductModel(
      id: 8,
      imagePath: 'assets/images/Plant.png',
      glbSource: 'assets/models/plant.glb',
      extraGlb: 'assets/models/plant2.glb',
      name: 'Plant ShowPiece',
      productType: 'Decoration',
      description: 'Product',
      primcolor: Color(0xfff174ed ),
      extracolor: Color(0xff4a7b7b),
    ),
  ];
}
